### ISSUE TITLE
Proyeccion plan de pruebas - cronograma

### ISSUE THREAD

**Issue by mimogollon1** [ISWPOLI/TransmiWeb#1]
**Se establecen los tiempos que se destinarán a las pruebas**

Se realiza el documento con la estimación de tiempo necesario para realizar las pruebas de la totalidad de los módulos del sistema.

- [ ] Elaboración del documento con cronograma de pruebas 

La prioridad de la historia es: media
El esfuerzo en tiempo es: 4

**Comment by cristian1297** [comment]
[CRONOGRAMA ACTIVIDADES-NOVIEMBRE.xlsx](https://github.com/ISWPOLI/TransmiWeb/files/1481073/CRONOGRAMA.ACTIVIDADES-NOVIEMBRE.xlsx)
